//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace PFdata.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DaysSupported {
            get {
                return ((bool)(this["DaysSupported"]));
            }
            set {
                this["DaysSupported"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool InterventionMin {
            get {
                return ((bool)(this["InterventionMin"]));
            }
            set {
                this["InterventionMin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AvgMin {
            get {
                return ((bool)(this["AvgMin"]));
            }
            set {
                this["AvgMin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool MissingBaseline {
            get {
                return ((bool)(this["MissingBaseline"]));
            }
            set {
                this["MissingBaseline"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ImprovementStatus {
            get {
                return ((bool)(this["ImprovementStatus"]));
            }
            set {
                this["ImprovementStatus"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DaysReported {
            get {
                return ((bool)(this["DaysReported"]));
            }
            set {
                this["DaysReported"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ServiceSite {
            get {
                return ((bool)(this["ServiceSite"]));
            }
            set {
                this["ServiceSite"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PromiseFellow {
            get {
                return ((bool)(this["PromiseFellow"]));
            }
            set {
                this["PromiseFellow"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("\"ActiveExited\"")]
        public string DataGridSplit {
            get {
                return ((string)(this["DataGridSplit"]));
            }
            set {
                this["DataGridSplit"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string RowItem {
            get {
                return ((string)(this["RowItem"]));
            }
            set {
                this["RowItem"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowInactive {
            get {
                return ((bool)(this["ShowInactive"]));
            }
            set {
                this["ShowInactive"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DisplayErrorPrompt {
            get {
                return ((bool)(this["DisplayErrorPrompt"]));
            }
            set {
                this["DisplayErrorPrompt"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SaveLog {
            get {
                return ((bool)(this["SaveLog"]));
            }
            set {
                this["SaveLog"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SendLog {
            get {
                return ((bool)(this["SendLog"]));
            }
            set {
                this["SendLog"] = value;
            }
        }
    }
}
